version: '3'
services:
        mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=declarausr
            - MONGO_INITDB_ROOT_PASSWORD=declarapsw
